name: CI/CD Pipeline with Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build files
        run: |
          mkdir -p dist
          echo "Sample build content" > dist/build.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Run tests
        run: |
          echo "Testing build files..."
          cat dist/build.txt

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Deploy (Simulation)
        run: |
          echo "Deploying files:"
          ls -R dist/
