name: CI/CD Pipeline with Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate files
        run: |
          mkdir -p dist
          echo "Hello, GitHub Actions!" > dist/output.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Verify files
        run: |
          echo "Checking files..."
          cat dist/output.txt

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Simulate deployment
        run: |
          echo "Deploying files:"
          ls -R dist/
